defaults:
  - env_vars: env_vars
  - model: lstm
  - _self_

data_collection_buffer_size: 300
tactile_buffer_size: 150
prediction_buffer_size: 10
diff_rate: 15
context_size: 7
max_diff: 100.0
device: cpu
task: handover

# model_pkl: "linear.pkl"
model_pkl: "eflesh_linear.pkl"
# model_weight_pth: "rotate_xy_mask"
slip_detection_freq: 50 # Hz
slip_detection_threshold: 0.8

robot_params:
  h: 0.6
  max_h: 0.06
  max_base: 0.08
  stretch_gripper_tight: -1.6
  abs_gripper: True
  rot_unit: axis

network:
  host: "127.0.0.1"
  remote: "127.0.0.1"
  reskin_port: 58588
  action_port: 8081
  flag_port: 2828

